theme: remote_theme: pages-themes/slate@v0.2.0
title: Sejal's WebSpace! 
description: Keep an eye out for my personal space. I'm about to publish some things which i'm learning! 
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jemoji
- karmadown
markdown: kramdown