# frozen_string_literal: true
source "https://rubygems.org"
gem "jemoji"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "webrick"
gem "kramdown-parser-gfm"
gem "kramdown"
gem "jekyll-remote-theme"
gem "jekyll-figure"