# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads/'
collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "select", default: "post", options: ['post', 'page', 'page_with_sidebar'], required: true}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Author", name: "author", widget: "string", default: "Sejal P", required: true}
      - label: "Featured Image"
        name: "image"
        widget: "image"
        default: "jedi.png"
        media_library:
          config:
            multiple: true
        required: false            
      - label: "Date"
        name: "date"
        widget: "date"
        default: ""
        format: "YYYY-MM-DD hh:mm:ss"
        required: true
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: "note" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Note" # Used in the UI, ie.: "New Post"
    folder: "_notes" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "select", default: "post", options: ['post', 'page'], required: true}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Author", name: "author", widget: "string", default: "Sejal P", required: true}
      - label: "Date"
        name: "date"
        widget: "date"
        default: ""
        format: "YYYY-MM-DD hh:mm:ss"
        required: true
      - {label: "Body", name: "body", widget: "markdown", required: true}      
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/nav.yml"
        fields:
          - label: "Navigation Items"
            name: "toc"
            widget: "list"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Url, name: url, widget: string}
  - name: "collections"
    label: "Collections"
    editor:
      preview: false
    files:
      - label: "Projects"
        name: "projects"
        file: "_data/projects_data.yml"
        fields:
          - label: "Project list"
            name: "projects"
            widget: "list"
            fields:
              - {label: Title, name: title, widget: string, required: true}
              - {label: Image, name: img, widget: image, required: false}
              - {label: Image Alt Text, name: img_alt, widget: string, required: true}
              - {label: About, name: about, widget: string, required: true}
              - {label: Link, name: link, widget: string, required: true}
      - label: "Skills"
        name: "skills"
        file: "_data/skills_data.yml"
        fields:
          - label: "Skills list"
            name: "skills"
            widget: "list"
            fields:
              - {label: Title, name: title, widget: string, required: true}
              - {label: Image, name: img, widget: image, required: false}
              - {label: "Level", name: "level", widget: "select", default: "pro", options: ['pro', 'fam'], required: true}
  # - name: "wallpapers"
  #   label: "Wallpapers"
  #   editor:
  #     preview: false
  #   files:
  #     - label: "Wallpapers"
  #       name: "wallpapers"
  #       file: "_data/wall.yml"
  #       fields:
  #         - label: "Files"
  #           name: "files"
  #           widget: "list"
  #           fields:
  #             - {label: Image, name: img, widget: image, required: true}